apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  namespace: labgke
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      hostname: redis
      containers:
      - name: web
        image: us-east1-docker.pkg.dev/xenon-music-338022/myfirstapp/myfirstapp:2.0
        env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: redis
          value: 127.0.0.1
        - name: MESSAGE
          value: "RAFAEL QUEIROZ - ATIVIDADE LAB GKE" 
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: myfirstapp-lb-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
